---
- name: Install latest version of theanorc
  shell: "{{ anaconda_path }}/bin/pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git"
  become: false

- name: Copy theanorc file to instance
  copy: src=theanorc dest=~/.theanorc
  become: false
